name = "MyPkg"
uuid = "0a37a943-8b95-4f61-a0ef-a579c62b4525"
authors = ["derrrobin <dieserrobin@outlook.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
